title: "WizardryAtWork"
email: contact@clayatownsend.com
tagline: "Clay Townsend - Network Engineer Digital Portfolio"
description: "Home for my links."
github_username:  yokoszn
twitter_username: yokoszn

baseurl: ""
url: "https://yokoszn.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
 # - index.md
 # - read-me.md
 # - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
